language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli@0.1.13 karma-cli@0.0.4
  - gem install sass
script: grunt travis
deploy:
  provider: s3
  access_key_id: AKIAI55AELZBPQKVIAXQ
  secret_access_key:
    secure: fDp97fUYc19sXmMnnp4OZL8MQYyTXRkxTVJj9NSdFI4xFCu34igwlcJXwHt9uuzV2wVIQ3R9GsAVfSwZxD+XWz1qrzWRt3PIsR5J7I9ZiqE0DaCK9IBVepsz5BR/A/q9v3VWGW7o+wy419EKVuXGHCJMAUoHeQCGeb8gOKYpI3g=
  bucket: ng-tags-input
  local-dir: build/travis
  skip_cleanup: true
  on:
    repo: mbenford/ngTagsInput
    branch: master
env:
  global:
    - secure: fTAoSkukYG14LWmA5iBU4+uGSAqNXIywVSQ3fzKJFLbHEnIv5B8Zi6z8Ka+IkX2QAE6HITR0jRM92VQ6ifS624+QtOl63Qfhv+DXnfyZow2poHgqfY1OaVI7aZJfc2mfEYINSqhcZSVC6vmUergDsYI9PW25SZNqDVnygrTggWM=
    - secure: OkD+Jv13JQ3fs+VgxQIGe/SiKQa4pMtjQj/j7beZvkx32gZSXpsZHZvNezWdejjj4sSszq8GeI5CrchxaKAcfDADd9rvv8F88bWF5ft4cUUGfCmI2jspn6B5yShHPbvRhjim0LZifZI6fZJ61N9l9jnEt69i9a+p+cXfrqY+OJA=
